name: tests
run-name: ensure main code quality
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-test:
    name: check-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '28'
          hexpm-mirrors: |
            https://builds.hex.pm
            https://cdn.jsdelivr.net/hex
          elixir-version: '1.19.3'
      - run: mix format

